### ISSUE TITLE
generated mid [3303] already in use, cannot register Exchange[R14]

### ISSUE THREAD

**Issue by rahulagarwal02** [eclipse/californium#1964]
I am using Californium CoAP library as a server. Client runs a Qt CoAP client.
Data rate is around 10 messages/sec
Client receives messages for almost 1.5 hr after which message stops coming.
Looking at logs getting below exception:

2022-03-21T11:02:28,516 WARN  [CoapServer(main)#1] {BaseCoapStack.java:115} - error send response CON-2.05   MID= 3303, Token=10F6A0C91DAF, OptionSet={"Observe":18992, "Content-Format":"text/plain"}, "{"fhr1":-32768,"fhr2":-3".. 116 bytes
java.lang.IllegalArgumentException: generated mid [3303] already in use, cannot register Exchange[R14]
	at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerWithMessageId(InMemoryMessageExchangeStore.java:245) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerOutboundResponse(InMemoryMessageExchangeStore.java:409) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.UdpMatcher.sendResponse(UdpMatcher.java:157) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendResponse(CoapEndpoint.java:1088) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendResponse(BaseCoapStack.java:236) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendResponse(ReliabilityLayer.java:153) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendResponse(BlockwiseLayer.java:624) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.stack.ObserveLayer.sendResponse(ObserveLayer.java:123) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendResponse(AbstractLayer.java:74) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.sendResponse(ExchangeCleanupLayer.java:83) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendResponse(BaseCoapStack.java:194) ~[californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.stack.BaseCoapStack.sendResponse(BaseCoapStack.java:110) [californium-core-2.6.3.jar:?]
	at org.eclipse.californium.core.network.CoapEndpoint$9.run(CoapEndpoint.java:912) [californium-core-2.6.3.jar:?]
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:289) [element-connector-2.6.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_242-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_242-internal]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_242-internal]

What could be the issue?

**Comment by boaks** [comment]
That indicates, that a outgoing message with MID 3303 is already "pending".

That either indicates, that the exchange-cleanup leaks (I'm not aware of such bugs), or "too much messages" are sent, which is either not indicated by the numbers you provided.

The MID is a 16 bit value, so usually 65000 messages could be sent. With a default EXCHANGE_LIFETIME of 247s that means "65000 in 247s".

If I use your values 1,5 h 10 msgs/s that results n 54000 messages at all. Did you adapt the value of EXCHANGE_LIFETIME? Could you please provide the used "Californium.properties"?

**Comment by boaks** [comment]
And consider to migrate to 3.4.0. :-).

**Comment by rahulagarwal02** [comment]
> That indicates, that a outgoing message with MID 3303 is already "pending".
> 
> That either indicates, that the exchange-cleanup leaks (I'm not aware of such bugs), or "too much messages" are sent, which is either not indicated by the numbers you provided.
> 
> The MID is a 16 bit value, so usually 65000 messages could be sent. With a default EXCHANGE_LIFETIME of 247s that means "65000 in 247s".
> 
> If I use your values 1,5 h 10 msgs/s that results n 54000 messages at all. Did you adapt the value of EXCHANGE_LIFETIME? Could you please provide the used "Californium.properties"?

Thanks for the response.
How does the exchange cleanup happens? I am using Qt CoAP client. Is there anything needs to be done on client side for cleanup?
Attaching the Californium.properties file.
[Californium.properties.txt](https://github.com/eclipse/californium/files/8409268/Californium.properties.txt)

**Comment by boaks** [comment]
> How does the exchange cleanup happens?

The implementation expects that `InMemoryMessageExchangeStore.remove(final KeyMID messageId, final Exchange exchange)` is called. On success path, that's done receiving the ACK for the CON Notify. if that ACK is missing, then the server is intended to cancel the observation and removes with that the exchange.

Do you always use CON notifies? Does your client reregister observes?

I'm not sure, what happens. Is it possible for you to provide a [CAPTURE](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#wireshark)? Only for the observe registration and a couple of notifies and ACKs. e.g. about 50 messages or so.

**Comment by rahulagarwal02** [comment]
> > How does the exchange cleanup happens?
> 
> The implementation expects that `InMemoryMessageExchangeStore.remove(final KeyMID messageId, final Exchange exchange)` is called. On success path, that's done receiving the ACK for the CON Notify. if that ACK is missing, then the server is intended to cancel the observation and removes with that the exchange.
> 
> Do you always use CON notifies? Does your client reregister observes?
> 
> I'm not sure, what happens. Is it possible for you to provide a [CAPTURE](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#wireshark)? Only for the observe registration and a couple of notifies and ACKs. e.g. about 50 messages or so.. 

Yes. Only using CON notify. When the issue happens, client detects and re-registers observer. 
Then messages start coming to client but stops again after around same time (1.5 hr)
I will try to get the capture.
Is there any log I can check to confirm if ACK is missing?

**Comment by boaks** [comment]
[RFC 7641 - 4.5.2 Advanced Transmission](https://datatracker.ietf.org/doc/html/rfc7641#section-4.5.2)

> For this purpose, the server MAY optimize the transmission process by
>    aborting the transmission of the old notification (but not before the
>    current transmission attempt is completed) and starting a new
>    transmission for the new notification (but with the retransmission
>    timer and counter of the aborted transmission retained).

and

`ACK_TIMEOUT=10000`

With that, a missing ACK would cause also a quiet phase of 10s and you will probably lose 100 notifies.

**Comment by boaks** [comment]
Without the capture, it will be very hard to reproduce this.
At least you will have to be very patient without capture, until I have time for searching for it.

**Comment by boaks** [comment]
Just to mention:

Beside the MID/Exchange house-keeping, the second source may be a call of [Message.setMID(int mid)](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/Message.java#L426) for some messages sent to that peer. You may check that.

**Comment by boaks** [comment]
I tried to reproduce it similar to your setup. Therefore I reduced the timer time 
[PlugtestServer Observe](https://github.com/eclipse/californium/blob/master/demo-apps/cf-plugtest-server/src/main/java/org/eclipse/californium/plugtests/resources/Observe.java#L60) from 5000 to 100.
Using [cf-browser-3.4.0](https://repo.eclipse.org/content/repositories/californium-releases/org/eclipse/californium/cf-browser/3.4.0/cf-browser-3.4.0.jar)  for the observing client didn't show the behavior you described.
If possible, you may also test you client against the modified plugtest-server?

**Comment by rahulagarwal02** [comment]
> Just to mention:
> 
> Beside the MID/Exchange house-keeping, the second source may be a call of [Message.setMID(int mid)](https://github.com/eclipse/californium/blob/master/californium-core/src/main/java/org/eclipse/californium/core/coap/Message.java#L426) for some messages sent to that peer. You may check that.

Checked that. We are not calling setMID

**Comment by rahulagarwal02** [comment]
> [RFC 7641 - 4.5.2 Advanced Transmission](https://datatracker.ietf.org/doc/html/rfc7641#section-4.5.2)
> 
> > For this purpose, the server MAY optimize the transmission process by
> > aborting the transmission of the old notification (but not before the
> > current transmission attempt is completed) and starting a new
> > transmission for the new notification (but with the retransmission
> > timer and counter of the aborted transmission retained).
> 
> and
> 
> `ACK_TIMEOUT=10000`
> 
> With that, a missing ACK would cause also a quiet phase of 10s and you will probably lose 100 notifies.

Once the exception which I had mentioned in the query occurs, after that notifies permanently stops coming until we re-register observer

**Comment by boaks** [comment]
> Once the exception which I had mentioned in the query occurs, after that notifies permanently stops coming until we re-register observer

Really strange ... I still have no guess, what have caused that ...
If possible, could you try to retest with your client and the modified plugtest-server as mentioned above?
Maybe, with the 3.4.0 first. If it doesn't appear there, then maybe with the 2.6.3 (but I would recommend to update to 3.4.0)

**Comment by rahulagarwal02** [comment]
> > Once the exception which I had mentioned in the query occurs, after that notifies permanently stops coming until we re-register observer
> 
> Really strange ... I still have no guess, what have caused that ... If possible, could you try to retest with your client and the modified plugtest-server as mentioned above? Maybe, with the 3.4.0 first. If it doesn't appear there, then maybe with the 2.6.3 (but I would recommend to update to 3.4.0)

Sure.. trying both the things. Will let you know the result. Thanks

**Comment by boaks** [comment]
> Checked that. We are not calling setMID

And you also don't reuse some "Response" instances? 

Anyway, I will add some diagnose to the 3.5.0, that in the future, it gets easier to see, if the MID is also provided outside of the mid-provider.

**Comment by boaks** [comment]
A first trace:
I used now a smaller time (25ms), below my RTT (30ms). That shows some unintended delays.

**Comment by rahulagarwal02** [comment]
Additional Info: We have 4 clients which registers observer to server for same end point. Out of these, 3 clients are using californium CoAP library. one client uses Qt CoAP library.
We are not facing any issues with californium clients. This issue occurs only with the client using Qt Coap Client

**Comment by boaks** [comment]
> We are not facing any issues with californium clients. This issue occurs only with the client using Qt Coap Client

That makes it hard for me to test. The QT Coap Client is your development? or is it public available?

**Comment by rahulagarwal02** [comment]
> > We are not facing any issues with californium clients. This issue occurs only with the client using Qt Coap Client
> 
> That makes it hard for me to test. The QT Coap Client is your development? or is it public available?
> 
> I assume, that even if the client makes something wrong, that triggers a bug on the server side. If that bug could be located, then it would be possible to fix it, at least for 3.5.0.

We are using a commercial license but it's available under GNU General Public license.
https://doc-snapshots.qt.io/qtcoap/index.html

**Comment by boaks** [comment]
Thanks. Do you know, if that test could be executed with the example client?

**Comment by boaks** [comment]
Are there binaries ready for download? I didn't find ones.

**Comment by boaks** [comment]
Just as additional idea.

```
DEDUPLICATOR_AUTO_REPLACE=true
```

retest with this set to `false`.

**Comment by boaks** [comment]
QT => 11 GB ... nightmare ...

**Comment by rahulagarwal02** [comment]
> Just as additional idea.
> 
> ```
> DEDUPLICATOR_AUTO_REPLACE=true
> ```
> 
> retest with this set to `false`.

ok.. will try it

**Comment by rahulagarwal02** [comment]
> (I wasn't able to build the client. So it will take some time, until I will try that again.)
> 
> Any update from your side? Does the issue occur using the modified plugtest-server?

We upgraded to 3.4.0 version and also tried with DEDUPLICATOR_AUTO_REPLACE as false. Still issue occurred.
Yet to try with the modified plugtest-server. Also trying to get the capture.

**Comment by boaks** [comment]
Any updates? Does "generated mid [3303] already in use, cannot register Exchange[R14]" occur with the plugtest-server?

**Comment by boaks** [comment]
Just to make sure, it's still the "generated mid [????] already in use, cannot register Exchange[???]"? yes?

And the issue occurs with the plugtest-server?

Are you using plain coap? Or coap over dtls?

**Comment by boaks** [comment]
I add the information about the other peer's identity to the diagnose message.

Please update to the current master.

And, also please report, if this occurs only with your server, or the plugtest-server as well.
If it doesn't occur with the plugtest-server, and your server doesn't set the MID, then maybe you use a specific `CoapEndpoint` setup. Therefore, please also report, if you use plain coap or coap over dtls.

**Comment by rahulagarwal02** [comment]
> I add the information about the other peer's identity to the diagnose message.
> 
> Please update to the current master.
> 
> And, also please report, if this occurs only with your server, or the plugtest-server as well. If it doesn't occur with the plugtest-server, and your server doesn't set the MID, then maybe you use a specific `CoapEndpoint` setup. Therefore, please also report, if you use plain coap or coap over dtls.

We are using plain coap. We are using coap for communication between services running on the same device. All the communication is on localhost.
Will let you know the result with plugtest-server soon.

**Comment by boaks** [comment]
> Will let you know the result with plugtest-server soon.

Any results update?

**Comment by rahulagarwal02** [comment]
> > Will let you know the result with plugtest-server soon.
> 
> Any results update?

Sorry for late response. Can you guide me how to use plugtest-server or is there any document I can refer.
To match with the actual scenario, server needs to create few endpoints. There will be multiple clients registering observers to these end points. From server we need to send data periodically every ~100 ms.

**Comment by rahulagarwal02** [comment]
I have got the capture but unable to attach the file. Even .zip file not getting attached.
Is there any other way to share it?

**Comment by boaks** [comment]
"drag and drop" doesn't work?

**Comment by rahulagarwal02** [comment]
> "drag and drop" just into the comment field doesn't work?

No.. tried multiple times

**Comment by boaks** [comment]
I tried it right now, works on my side.
How large is your zip? (And it has the ending ".zip")?

**Comment by boaks** [comment]
And it is the capture from the plugstest-server?

**Comment by rahulagarwal02** [comment]
> And it is the capture from the plugstest-server?

No.. its from the actual server and client where we are seeing the issue

**Comment by rahulagarwal02** [comment]
> I tried it right now, works on my side. How large is your zip? (And it has the ending ".zip")?

Its 25 MB

**Comment by boaks** [comment]
With the plugtest server the issue can't be reproduced? 
Or do you need some instructions?

**Comment by rahulagarwal02** [comment]
> With the plugtest server the issue can't be reproduced? Or do you need some instructions?

Yes. Need some inputs on how to use it.

**Comment by boaks** [comment]
25MB, I'm not sure, if that helps. At least I would not try to read through. I would propose, that you try to select the coap messages from the client, where the issue occurs. And then just the messages with the reported MID.
See [wireshark](https://github.com/eclipse/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#wireshark).

But before that, you should check the plugtest-server.

**Comment by boaks** [comment]
> Yes. Need some inputs on how to use it.

1. Pleased adapt the timer interval of the observe in the plugtest-server from 5000ms to 100ms, changing it locally (demo-apps/cf-plugtest-server) . [PlugtestServer Observe](https://github.com/eclipse/californium/blob/master/demo-apps/cf-plugtest-server/src/main/java/org/eclipse/californium/plugtests/resources/Observe.java#L60).
2. mvn clean install in the parents folder.
3. cd to (demo-apps/cf-plugtest-server)
4. java -jar target/cf-plugtest-server-3.5.0-SNAPSHOT.jar

Server should start.

5. use your client and start the observer for "coap://<host>/obs"
6. check, that you receive notifies about every 100ms
7. Wait until the issue occurs (or not)

**Comment by boaks** [comment]
Maybe, there is one more source of "generated mid [3303] already in use, cannot register Exchange":
reusing a `Message`, I guess here the `Response`. The first time the `Response` instance is sent, a MID is assigned to that `Response` instance. If then, later the instance is "reused" (which is not considered to be valid), then it may register the old MID. At that point in time, it's OK. If now the auto-generated MID gets the same value, the the error is reported.
So, please check, if you always create a fresh `Response`.

**Comment by boaks** [comment]
Any reason to start with a NON observer request? That is responded also with a NON response, which has the same MID as the last CON notify. At least a first idea, what may cause the trouble in Californium.
Maybe, until that gets analyzed (and fixed, if wrong), you can try to use a CON request to start the observation?

(Additionally, the empty ACKs are including tokens, which doesn't makes sense. Maybe worth to report that to report that there.)

**Comment by boaks** [comment]
I added a unit test for the GET/NON and Notify/CON. I still can't reproduce the issue.

Are you able to reproduce it with the plugtest-server?

**Comment by rahulagarwal02** [comment]
> Any reason to start with a NON observer request? That is responded also with a NON response, which has the same MID as the last CON notify. At least a first idea, what may cause the trouble in Californium. Maybe, until that gets analyzed (and fixed, if wrong), you can try to use a CON request to start the observation?
> 
> (Additionally, the empty ACKs are including tokens, which doesn't makes sense. Maybe worth to report that to report that there.)

I am trying with CON request to start the observation. Will let you know the result.

**Comment by boaks** [comment]
Just in the case, you're still on it.
I merged PR #1986. I f you update to the current master, you may need to adapt the 
"Californium???3.properties" and set the new

``` 
COAP.STRICT_EMPTY_MESSAGE_FORMAT=false
``` 
 
(or just add that line to the already create "Californium???3.properties".)

Just in the case, CON works and you not longer on it, please close the issue.

I tried to reproduce it, but at least until now, I wasn't successful. And until now, you also didn't confirm, that this occurs with the Plugtest-Server. So I'm not sure, if it is more an issue of your implementation of that resource or really a Californium issue.

**Comment by rahulagarwal02** [comment]
> Just in the case, you're still on it. I merged PR #1986. If you update to the current master, you may need to adapt the "Californium???3.properties" and set the new
> 
> ```
> COAP.STRICT_EMPTY_MESSAGE_FORMAT=false
> ```
> 
> (or just add that line to the already create "Californium???3.properties".)
> 
> Just in the case, CON works and you not longer on it, please close the issue.
> 
> I tried to reproduce it, but at least until now, I wasn't successful. And until now, you also didn't confirm, that this occurs with the Plugtest-Server. So I'm not sure, if it is more an issue of your implementation of that resource or really a Californium issue.

We tried with the CON request but the issue is still not resolved. We followed your instructions for plugtest server.
Now able to run the plugtest server and getting data on the client side. Test is in progress, will let you know the result.

**Comment by boaks** [comment]
> We tried with the CON request but the issue is still not resolved. 

Really hard to say, what goes wrong. Looking forward to the plugtest-server result.

**Comment by rahulagarwal02** [comment]
> > We tried with the CON request but the issue is still not resolved.
> 
> Really hard to say, what goes wrong. Looking forward to the plugtest-server result.

This issue occurs only when there are multiple clients and the clients are registering observers on multiple endpoints.
With Single client or number of endpoints 3 or lesser we have not faced this issue. So need to look around what could go wrong when there are more clients and end points

**Comment by boaks** [comment]
That points for more in to the direction of your implementation.

Let me explain:
The MIDs are only scoped to one endpoint, means, if you have more clients or one, should not be the issue.
But, if you start to reuse a `Message` (here I guess a `Response`), then you break Californium's API.

Really looking forward to your results.
Just to mention: PR #1987 prevents now a application from resending a `Message`.

**Comment by boaks** [comment]
I release the 3.5.0 today. 
if you now want to test with the [plugtest-server](https://repo.eclipse.org/content/repositories/californium-releases/org/eclipse/californium/cf-plugtest-server/3.5.0/cf-plugtest-server-3.5.0.jar) it's easier and the server itself works "out-of-the-box" for your test (OK, "close to out-of-the-box", because of the "non-compliant empty-messages" . You need to adapt your client to use "coap://<host>/obs", that's it.

Download the server via the link above. it supports now the cli-option "--notify-interval".

```
java -jar cf-plugtest-server-3.5.0.jar --notify-interval=100[ms]
``` 

Stop it with CTRL-C and then edit "CaliforniumPlugtest3.properties" and adapt

``` 
# Process empty messages strictly according RFC7252, 4.1 as format error.
# Disable to ignore additional data as tokens or options.
# Default: true
COAP.STRICT_EMPTY_MESSAGE_FORMAT=true
``` 

to `false`.

Looking forward to your results with the plugtest-server.

**Comment by rahulagarwal02** [comment]
> I released the 3.5.0 today. if you now want to test with the [plugtest-server](https://repo.eclipse.org/content/repositories/californium-releases/org/eclipse/californium/cf-plugtest-server/3.5.0/cf-plugtest-server-3.5.0.jar) it's easier and the server itself works "out-of-the-box" for your test (OK, "close to out-of-the-box", because of the "non-compliant empty-messages" . You need to adapt your client to use "coap:///obs", that's it.
> 
> Download the server via the link above. it supports now the cli-option "--notify-interval".
> 
> ```
> java -jar cf-plugtest-server-3.5.0.jar --notify-interval=100[ms]
> ```
> 
> Stop it with CTRL-C and then edit "CaliforniumPlugtest3.properties" and adapt
> 
> ```
> # Process empty messages strictly according RFC7252, 4.1 as format error.
> # Disable to ignore additional data as tokens or options.
> # Default: true
> COAP.STRICT_EMPTY_MESSAGE_FORMAT=true
> ```
> 
> to `false`.
> 
> Looking forward to your results with the plugtest-server.

Ok. Will try this.
We tried with the plugtest-server but issue did not occur with one end point. We are trying to increase the number of end points in plugtest-server and see if it gets reproduced.

**Comment by rahulagarwal02** [comment]
> Any reason to start with a NON observer request? That is responded also with a NON response, which has the same MID as the last CON notify. At least a first idea, what may cause the trouble in Californium. Maybe, until that gets analyzed (and fixed, if wrong), you can try to use a CON request to start the observation?
> 
> (Additionally, the empty ACKs are including tokens, which doesn't makes sense. Maybe worth to report that to report that there.)

I have some good news. Using CON request to start the observation fixed the issue we were observing.
Last time when we tried looks like there was some problem with the setup. We tried couple of times again and it's working.
Thanks a lot for your support.

**Comment by boaks** [comment]
Thanks for all your tests.

If you want to close this issue, please do so.
If you want to continue to search for the root-cause, please try to reproduce it with the plugtest-server and NON request and CON notifies.

**Comment by rahulagarwal02** [comment]
I will close this issue for now.
Will let you know if we could reproduce the issue with plugtest-server.

**Comment by boaks** [comment]
Thanks!
I appreciate your patience. 

Just one remark:

The QT client uses malformed ACKs.

[RFC 7252 - 4.1. Messages and Endpoints](https://www.rfc-editor.org/rfc/rfc7252.html#section-4.1)

> An Empty message has the Code field set to 0.00.  The Token Length
>    field MUST be set to 0 and bytes of data MUST NOT be present after
>    the Message ID field.  If there are any bytes, they MUST be processed
>    as a message format error.

But the QT client adds a token to a empty ACK.

![wireshark-ACK](https://user-images.githubusercontent.com/10937819/165456052-b38b28af-99ec-48fc-8dde-5c4923de664d.png)

The issue with that is, that if Californium relaxes the processing, and ignore the "MUST be processed as a message format error", then someone may consider it as non-compliant. Therefore I fixed that in the last days and added a configuration (STRICT_EMPTY_MESSAGE_FORMAT) for a relaxed backwards compatibility.

Some weeks ago, when I tired to contact QT about offering a binary download for their client, only got back the question about my customer number. If you have such a customer number, maybe you contact them and report that compliant issue.

[ack.pcap.gz](https://github.com/eclipse/californium/files/8569382/ack.pcap.gz)

**Comment by rahulagarwal02** [comment]
Sure. I will raise report this issue to Qt. Thanks

**Comment by boaks** [comment]
I spent some time in a redesign of the observe server-side.
I still didn't find any stuff, which would have caused your issue, except your `CoapResource` does something different.

See PR #2014 for the redesign.
I consider to merge it next week.
Currently I have no time schedules for the 3.6,  maybe end of May or end of June.
So, depending on your interest and time, your feedback is welcome, especially, if it breaks something.

One hint: if you want to retest your issue, you may set

```
# Base MID for multicast requests.
# Default: 65000
COAP.MULTICAST_BASE_MID=1000
```
The would cause the server to reuse the none-multicast MIDs after only 1000 messages and should therefore speed up your test.

**Comment by boaks** [comment]
Any news on this topic?

I scheduled release 3.6.0 for this week, Thursday. So, if there is something left from this issue, let us know.

**Comment by rahulagarwal02** [comment]
Thanks for reaching out.
We used CON request to start the observation which fixed the issue. 
After this change we did not face any issue on our device. We are sticking with this fix as of now. Haven't tried anything else.
